name: Test Calculator With Sprkl

on: 
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    branches:
      - '**'

jobs:
  run-tests-with-sprkl:
    runs-on: ubuntu-latest
    name: Installing Sprkl Testing

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Sprkl Setup
        uses: sprkl-dev/sprkl-action/setup@v0.0.44
        with:
          token: ${{ secrets.USE_SPRKL_CI_TOKEN }}
          setenv: false

      - name: Setup pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build Calculator-Service
        run: pnpm build
        
      - name: Run tests
        run: pnpm test
        env: 
          SPRKL_RECIPE: all